### ISSUE TITLE
Migration Error

### ISSUE THREAD

**Issue by nitech** [tasdev-au/craft-fulfillments#14]
Getting this error when installing on Craft CMS 4.8.9, Craft Commerce 4.5.2

![image](https://github.com/tasdev-au/craft-fulfillments/assets/1279436/abe6eb76-c349-433f-9695-9d686ae5a43f)

Migration Error: An error occurred while executing the "tasdev\orderfulfillments\migrations\Install migration: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'orderfulfillments_fulfillments' already exists
The SQL being executed was: CREATE TABLE orderfulfillments_fulfillments (
id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
orderId int(11) NOT NULL,
trackingNumber varchar(255),
trackingCarrierClass varchar(255),
trackingCarrierId int(11),
dateCreated datetime(0) NOT NULL,
dateUpdated datetime(0) NOT NULL,
uid char(36) NOT NULL DEFAULT '0'
) ENGINE = InnoDb DEFAULT CHARACTER SET = utf8

**Comment by jaydensmith** [comment]
@nitech the Install migration shouldn't be running again, can you check it is in your `migrations` table?

**Comment by nitech** [comment]
I can't see anything in the migrations table related to plugin:fulfillments or plugin:orderfulfillments. 

To backtrack a bit, I got another error message when I first installed the fulfillments plugin. I then uninstalled. I assume the records inside migraitons were removed then, but somehow the tables were not removed: 

![image](https://github.com/tasdev-au/craft-fulfillments/assets/1279436/e99286e2-d54b-4679-aa57-cb965b9db238)

The plugin is not present in `plugins` either. 

I decided to remove the plugin's tables manually and then reinstall. Now I see the original error: 

```
Migration Error: An error occurred while executing the "tasdev\orderfulfillments\migrations\Install migration: Typed property tasdev\orderfulfillments\models\Carrier::$legacyClass must not be accessed before initialization
```

From web.log:

```
2024-04-15 09:31:43 [web.ERROR] [craft\db\MigrationManager::migrateUp] Failed to apply Install (time: 0.285s). Output:
    > create table {{%orderfulfillments_fulfillments}} ... done (time: 0.014s)
    > create table {{%orderfulfillments_fulfillment_lines}} ... done (time: 0.014s)
    > create table {{%orderfulfillments_carriers}} ... done (time: 0.014s)
    > create index idx_wrtjajwueakseiqzwbhltaseoxruxrdarqdk on {{%orderfulfillments_fulfillments}} (orderId) ... done (time: 0.015s)
    > create index idx_dafuyrepwporqkxfpdiyilistbxhpvfqdcjb on {{%orderfulfillments_fulfillments}} (trackingCarrierId) ... done (time: 0.013s)
    > create index idx_qzbmkwhtzxylpeadziajaibwbxocublulhjh on {{%orderfulfillments_fulfillment_lines}} (lineItemId) ... done (time: 0.013s)
    > create index idx_dbmouhkesdewdhwyjxjpznefzxdhqgsyuylq on {{%orderfulfillments_fulfillment_lines}} (fulfillmentId) ... done (time: 0.010s)
    > create index idx_ikkbxwlekckxnysvkcdmoovnuxsizdkroiwp on {{%orderfulfillments_fulfillment_lines}} (fulfillmentId) ... done (time: 0.013s)
    > add foreign key fk_neesfnnjzmkwlpqtkcxzotwoklhqafpskiiq: {{%orderfulfillments_fulfillments}} (orderId) references {{%commerce_orders}} (id) ... done (time: 0.036s)
    > add foreign key fk_bkoprzltrxwsliudtucmokfflrrkfgmufxjw: {{%orderfulfillments_fulfillments}} (trackingCarrierId) references {{%orderfulfillments_carriers}} (id) ... done (time: 0.045s)
    > add foreign key fk_ranntqjmujivzxzuhuebkerqlzshuzaxbphc: {{%orderfulfillments_fulfillment_lines}} (lineItemId) references {{%commerce_lineitems}} (id) ... done (time: 0.050s)
    > add foreign key fk_toiqirqqzhaonoyzdmejtilmsaazwutfkurr: {{%orderfulfillments_fulfillment_lines}} (fulfillmentId) references {{%orderfulfillments_fulfillments}} (id) ... done (time: 0.041s)
Exception: Typed property tasdev\orderfulfillments\models\Carrier::$legacyClass must not be accessed before initialization (/var/www/html/vendor/tasdev-au/craft-fulfillments/src/services/Carriers.php:181)
#0 /var/www/html/vendor/tasdev-au/craft-fulfillments/src/migrations/Install.php(191): tasdev\orderfulfillments\services\Carriers->saveCarrier(Object(tasdev\orderfulfillments\models\Carrier))
#1 /var/www/html/vendor/tasdev-au/craft-fulfillments/src/migrations/Install.php(39): tasdev\orderfulfillments\migrations\Install->insertDefaultData()
#2 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(49): tasdev\orderfulfillments\migrations\Install->safeUp()
#3 /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#4 /var/www/html/vendor/craftcms/cms/src/base/Plugin.php(144): craft\db\MigrationManager->migrateUp(Object(tasdev\orderfulfillments\migrations\Install))
#5 /var/www/html/vendor/craftcms/cms/src/services/Plugins.php(533): craft\base\Plugin->install()
#6 /var/www/html/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(573): craft\services\Plugins->installPlugin('order-fulfillme...', 'standard')
#7 /var/www/html/vendor/craftcms/cms/src/controllers/pluginstore/InstallController.php(65): craft\controllers\BaseUpdaterController->installPlugin('order-fulfillme...', 'standard')
#8 [internal function]: craft\controllers\pluginstore\InstallController->actionCraftInstall()
#9 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#11 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('craft-install', Array)
#12 /var/www/html/vendor/craftcms/cms/src/web/Application.php(341): yii\base\Module->runAction('pluginstore/ins...', Array)
#13 /var/www/html/vendor/craftcms/cms/src/web/Application.php(642): craft\web\Application->runAction('pluginstore/ins...', Array)
#14 /var/www/html/vendor/craftcms/cms/src/web/Application.php(303): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#15 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#16 /var/www/html/web/index.php(21): yii\base\Application->run()
#17 {main}
 {"memory":30690992} 
2024-04-15 09:31:43 [web.ERROR] [craft\controllers\BaseUpdaterController::installPlugin] Plugin installation failed: An error occurred while executing the "tasdev\orderfulfillments\migrations\Install migration: Typed property tasdev\orderfulfillments\models\Carrier::$legacyClass must not be accessed before initialization {"memory":30705288} 
```
It seems the issue might be with `Carrier.php:61` not being initialized. This might have to do with the version of PHP I am running (which is 8.0).

Anyways. I modified Carrier.php:61 and set it to `public ?string $legacyClass = null;`, ran `ddev craft plugin/install order-fulfillments` and now it works.

**Comment by nitech** [comment]
Also, please add the carrier Bring to the default list of carriers: 

```
<?php
/**
 * Fulfillments plugin for Craft CMS 3.x
 *
 * Add Shopify like fulfillments to your Craft Commerce orders.
 *
 */

namespace namespace modules\sitemodule\extensions;

use Craft;
use tasdev\orderfulfillments\base\TrackingCarrier;

/**
 * @author    Jayden Smith
 * @package   Fulfillments
 * @since     1.0.0
 */
class Bring extends TrackingCarrier
{
    // Public Methods
    // =========================================================================

    /**
     * Returns the display name of the carrier.
     *
     * @return string
     */
    public function getName(): string
    {
        return Craft::t('order-fulfillments', 'Bring');
    }

    /**
     * Returns the tracking URL for the carrier formatted with the tracking number.
     *
     * @return string
     */
    public function getTrackingUrl(): string
    {
        return "https://tracking.bring.com/tracking/{$this->trackingNumber}";
    }
}
```

**Comment by jaydensmith** [comment]
@nitech what version of the plugin are you using? In the latest version the carriers are now managed via the plugin settings.

**Comment by nitech** [comment]
I was using 4.1.0. I see no "new" button in the carriers list: 

![image](https://github.com/tasdev-au/craft-fulfillments/assets/1279436/ff773132-006d-4133-925f-aa588f79016b)

**Comment by jaydensmith** [comment]
@nitech my bad, this should be fixed now.

**Comment by nitech** [comment]
Thanks, it works now.
