### ISSUE TITLE
Twig Runtime Error (Craft 4)

### ISSUE THREAD

**Issue by AndrewMac** [tasdev-au/craft-fulfillments#8]
Hi Jayden

I've updated my site to Craft 4, but when I try to access a user account I get the following error:

```
Twig\Error\RuntimeError: Key "heading" for array with keys "order-fulfillments-viewFulfillments, order-fulfillments-createFulfillments, order-fulfillments-deleteFulfillments" does not exist. in /var/www/html/vendor/craftcms/cms/src/templates/_includes/permissions.twig:77
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/helpers/Template.php(101): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Array, 'heading', Array, 'any', false, false)
#1 /var/www/html/storage/runtime/compiled_templates/29/29d7af8e9258880dae5b763a62596ced.php(83): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Array, 'heading', Array)
#2 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_5041ba0939a3509c671e4c1033454e7d->doDisplay(Array, Array)
#3 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#4 /var/www/html/storage/runtime/compiled_templates/06/06932c1e0cdc51e89542a73ab8c3782e.php(367): Twig\Template->display(Array)
#5 /var/www/html/vendor/twig/twig/src/Template.php(171): __TwigTemplate_cabfe60c6ee47198759c588809b00331->block_content(Array, Array)
#6 /var/www/html/storage/runtime/compiled_templates/43/437e34aca32b47e243585c3aa8808c0d.php(561): Twig\Template->displayBlock('content', Array, Array)
#7 /var/www/html/vendor/twig/twig/src/Template.php(171): __TwigTemplate_f9ec3161612bdf9a4fc3cf4340817e7a->block_main(Array, Array)
#8 /var/www/html/storage/runtime/compiled_templates/43/437e34aca32b47e243585c3aa8808c0d.php(353): Twig\Template->displayBlock('main', Array, Array)
#9 /var/www/html/vendor/twig/twig/src/Template.php(171): __TwigTemplate_f9ec3161612bdf9a4fc3cf4340817e7a->block_body(Array, Array)
#10 /var/www/html/storage/runtime/compiled_templates/0b/0b2fd89461500d8daeddaf109c4b55a0.php(96): Twig\Template->displayBlock('body', Array, Array)
#11 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_3eda642b0be9ac6f76551a654f41df6e->doDisplay(Array, Array)
#12 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#13 /var/www/html/storage/runtime/compiled_templates/3a/3af65a6056753d9515493aa2ccec9dfb.php(56): Twig\Template->display(Array, Array)
#14 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_ada4250223d2f13f02e9828c109eca9f->doDisplay(Array, Array)
#15 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#16 /var/www/html/storage/runtime/compiled_templates/43/437e34aca32b47e243585c3aa8808c0d.php(172): Twig\Template->display(Array, Array)
#17 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_f9ec3161612bdf9a4fc3cf4340817e7a->doDisplay(Array, Array)
#18 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#19 /var/www/html/storage/runtime/compiled_templates/06/06932c1e0cdc51e89542a73ab8c3782e.php(116): Twig\Template->display(Array, Array)
#20 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_cabfe60c6ee47198759c588809b00331->doDisplay(Array, Array)
#21 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#22 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#23 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#24 /var/www/html/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#25 /var/www/html/vendor/craftcms/cms/src/web/View.php(414): Twig\Environment->render('users/_edit', Array)
#26 /var/www/html/vendor/craftcms/cms/src/web/View.php(467): craft\web\View->renderTemplate('users/_edit', Array)
#27 /var/www/html/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(52): craft\web\View->renderPageTemplate('users/_edit', Array, 'cp')
#28 /var/www/html/vendor/yiisoft/yii2/web/Response.php(1095): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#29 /var/www/html/vendor/craftcms/cms/src/web/Response.php(275): yii\web\Response->prepare()
#30 /var/www/html/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#31 /var/www/html/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#32 /var/www/html/web/index.php(12): yii\base\Application->run()
#33 {main}
```

**Comment by jaydensmith** [comment]
Hi @AndrewMac, I didn't catch that the permissions structure had changed with Craft 4. I've just updated that now, sorry,

**Comment by AndrewMac** [comment]
No worries at all! I am just so impressed by how quickly you get around to fixing these issues!
Thanks so much, I really appreciate it :-)
